create table if not exists "2018"(
	hotel varchar (10),
	is_canceled integer, 
	lead_time integer,
	arrival_date_year integer,
	arrival_date_month varchar (10),
	arrival_date_week_number integer,
	arrival_date_day_of_month integer,
	stays_in_weekend_nights integer,
	stays_in_week_nights integer,
	adults integer,
	children integer,
	babies integer,
	meal varchar (10),
	country varchar (10),
	market_segment varchar (20),
	distribution_channel varchar (10),
	is_repeated_guest integer,
	previous_cancellations integer,
	previous_bookings_not_canceled integer,
	reserved_room_type varchar (10),
	assigned_room_type varchar (10),
	booking_changes integer,
	deposit_type varchar (20),
	agent integer,
	company integer,
	days_in_waiting_list integer,
	customer_type varchar (10),
	adr numeric (5,2),
	required_car_parking_spaces integer,
	total_of_special_requests integer,
	reservation_status varchar (10),
	reservation_status_date timestamp
); 

create table if not exists "2019"(
	hotel varchar (10),
	is_canceled integer, 
	lead_time integer,
	arrival_date_year integer,
	arrival_date_month varchar (10),
	arrival_date_week_number integer,
	arrival_date_day_of_month integer,
	stays_in_weekend_nights integer,
	stays_in_week_nights integer,
	adults integer,
	children integer,
	babies integer,
	meal varchar (10),
	country varchar (10),
	market_segment varchar (20),
	distribution_channel varchar (10),
	is_repeated_guest integer,
	previous_cancellations integer,
	previous_bookings_not_canceled integer,
	reserved_room_type varchar (10),
	assigned_room_type varchar (10),
	booking_changes integer,
	deposit_type varchar (20),
	agent integer,
	company integer,
	days_in_waiting_list integer,
	customer_type varchar (10),
	adr numeric (5,2),
	required_car_parking_spaces integer,
	total_of_special_requests integer,
	reservation_status varchar (10),
	reservation_status_date timestamp
); 

create table if not exists "2020"(
	hotel varchar (10),
	is_canceled integer, 
	lead_time integer,
	arrival_date_year integer,
	arrival_date_month varchar (10),
	arrival_date_week_number integer,
	arrival_date_day_of_month integer,
	stays_in_weekend_nights integer,
	stays_in_week_nights integer,
	adults integer,
	children integer,
	babies integer,
	meal varchar (10),
	country varchar (10),
	market_segment varchar (20),
	distribution_channel varchar (10),
	is_repeated_guest integer,
	previous_cancellations integer,
	previous_bookings_not_canceled integer,
	reserved_room_type varchar (10),
	assigned_room_type varchar (10),
	booking_changes integer,
	deposit_type varchar (20),
	agent integer,
	company integer,
	days_in_waiting_list integer,
	customer_type varchar (10),
	adr numeric (5,2),
	required_car_parking_spaces integer,
	total_of_special_requests integer,
	reservation_status varchar (10),
	reservation_status_date timestamp
); 

create table if not exists meal_cost(
	Cost numeric (5,2),
meal varchar (10) PRIMARY KEY);

create table if not exists market_segment(
	Discount numeric (5,2),
	market_segment varchar (10) PRIMARY KEY);


